name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version (e.g., v1.2.3)'
        required: true
      release_name:
        description: 'The display name for the release'
        required: true
      prerelease:
        description: 'Is this a pre-release? (true/false)'
        required: true
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.release_name }}
          generate_release_notes: true
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
